### ISSUE TITLE
Update link for GApps with LineageOS20-ATV to MindTheGapps?

### ISSUE THREAD

**Issue by Namyts** [KonstaT/KonstaT.github.io#15]
Hi,

In /_devices/rpi4/LineageOS20-ATV.md it says 
> Q: How to install Google apps?
> _A: It's still very early days for Android TV 13 so I'm not aware there is currently any compatible GApps releases available._

It looks like MindTheGApps has a solution, and it is linked https://wiki.lineageos.org/gapps here.

The link to the actual zip is: https://androidfilehost.com/?fid=4279422670115716786

I am im the processing of testing this combination

**Comment by Namyts** [comment]
Never mind, it looks like it might not work afterall. After installing MindTheGApps the device boots into LineageOS again, but after setting up internet & bluetooth accessories it shows a blue screen and nothing changes. It has been around 30 minutes now.

**Comment by KonstaT** [comment]
Current MindTheGapps Android TV releases are broken for the Pi at least. Correct place to report this would be https://gitlab.com/MindTheGapps/vendor_gapps_tv.

For Android 12 the older working releases can be found here: https://androidfilehost.com/?w=files&flid=335898

For Android 13 you need to modify the update-binary inside the GApps package. There's instructions and modified package posted on the comments on my site.
http://disq.us/p/2t0b2zv
http://disq.us/p/2sztoq7
http://disq.us/p/2tc6tot

Closing as I'll naturally update this information if/when there's a working package available.

**Comment by Namyts** [comment]
Thanks, can confirm the adjustments to MindTheGApps linked in the discussions fix the issue!

**Comment by Namyts** [comment]
I have created [an issue in the MindTheGapps repo](https://gitlab.com/MindTheGapps/vendor_gapps_tv/-/issues/1), hopefully they'll be able to do something about it so that everyone trying to setup Android TV with the Play Store on their Raspberry Pis won't have to manually edit the zip file

**Comment by Namyts** [comment]
Looks like someone else in the discussions has [created a merge request already](https://gitlab.com/MindTheGapps/vendor_gapps_tv/-/merge_requests/3)
