### ISSUE TITLE
trying to find lineage-17.1-20201108-UNOFFICIAL-KonstaKANG-rpi3.zip

### ISSUE THREAD

**Issue by nospam2k** [KonstaT/KonstaT.github.io#16]
I'm sorry to break into your github like this, but I'm looking for lineage-17.1-20201108-UNOFFICIAL-KonstaKANG-rpi3.zip. I can't find it anywhere and androidfilehost says no mirrors. Thanks for you patience!

**Comment by KonstaT** [comment]
AndroidFileHost has random issues sometimes. Try refreshing the download page, try using different browser, or try again later.

Seems to be working for me just now at least.

**Comment by fb080345** [comment]
AndroidFileHost上不能下载
